FROM ghcr.io/haoweich/ops_pixel_rom/run-on-arch-haoweich-ops-pixel-rom--github-workflows-base-image-yaml-aarch64-ubuntu20-04:latest

ENV DEBIAN_FRONTEND=noninteractive

#WORKDIR /root
#
#COPY scripts/00-setup.sh .
#COPY scripts/01-pull.sh .
#
#RUN ./00-setup.sh && ./01-pull.sh